In [5]:
# numpy library import
import numpy as np

In [29]:
# 1. 1차원 배열 (원소가 0 ~ 9의 값)을 만들고 출력하시오

# Console Output
# ---------------------------------------------
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# 2. 1차원 배열인 arr에서 홀수 원소값을 추출하여 출력하시오

# Console Output
# ---------------------------------------------
# array([1, 3, 5, 7, 9])

# input data
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 홀수 data 추출
arr_odd = np.array([1, 3, 5, 7, 9])

arr[arr_odd]

array([1, 3, 5, 7, 9])

In [32]:
# 3. 1차원 배열인 arr에서 홀수 원소값을 -1로 변경하여 출력하시오

# Console Output
# ---------------------------------------------
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# input data
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 홀수 원소값을 -1로 변경
arr_out = np.where(arr % 2 == 1, -1, arr)
arr_out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [33]:
# 4. 1차원 배열 (원소가 0 ~ 9의 값)을 2차원 배열 (2,5)로 변환하여 출력하시오

# Console Output
# ---------------------------------------------
# array([[0, 1, 2, 3, 4],
#       [5, 6, 7, 8, 9]])

# input data
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2차원 배열로 변경
arr_out = arr.reshape(2, 5)
arr_out

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
# 5. 2개의 배열 a, b를 vertically 합쳐 출력하시오

# Console Output
# ---------------------------------------------
# array([[0, 1, 2, 3, 4],
#        [5, 6, 7, 8, 9],
#        [1, 1, 1, 1, 1],
#        [1, 1, 1, 1, 1]])

# input data
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,5)

# a, b를 vertically 합침
arr_out = np.vstack((a, b))
arr_out

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
# 5. 2개의 배열 a, b를 horizontally 합쳐 출력하시오

# Console Output
# ---------------------------------------------
# array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# input data
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,5)

# a, b를 horizontally 합침
arr_out = np.hstack((a, b))
arr_out

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [48]:
# 6. 2차원 배열에서 첫번째 행과 두번째 행의 순서를 바꿔 출력하시오

# Console Output
# ---------------------------------------------
# array([[3, 4, 5],
#        [0, 1, 2],
#        [6, 7, 8]])

# input data
arr = np.arange(9).reshape(3,3)

# 2차원 배열에서 첫번째 행과 두번째 행의 순서를 바꿈
arr_out = arr[[1,0,2]]
arr_out

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [44]:
# 7. 2차원 배열에서 행 전체 순서를 reverse로 바꿔 출력하시오

# Console Output
# ---------------------------------------------
# array([[6, 7, 8],
#        [3, 4, 5],
#        [0, 1, 2]])

# input data
arr = np.arange(9).reshape(3,3)

# 2차원 배열에서 행 전체 순서를 reverse로 바꿈
arr_out = arr[::-1]
arr_out

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [46]:
# 8. 2차원 배열에서 column 전체 순서를 reverse로 바꿔 출력하시오

# Console Output
# ---------------------------------------------
# array([[2, 1, 0],
#        [5, 4, 3],
#        [8, 7, 6]])

# input data
arr = np.arange(9).reshape(3,3)

# 2차원 배열에서 column 전체 순서를 reverse로 바꿈
arr_out = arr[:, ::-1]
arr_out

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])