In [13]:
# numpy library import
import numpy as np

In [14]:
# data1 => list data type
data1 = [1,2,3,4,5,6]
print(data1)

[1, 2, 3, 4, 5, 6]


In [20]:
# numpy를 이용하여 array 정의하기
arr1 = np.array((1,2,3,4,5,6))
print (arr1)
# arr1의 data type : ndarray
print (type(arr1))
# array의 원소의 자료형(data type)을 확인할 수 있다.
print (arr1.dtype)

# array의 형태(크기)를 확인할 수 있다.
print (arr1.shape)

# arr1의 첫번째 원소값 출력하기
print (arr1[0])
# arr1의 세번째 원소값 출력하기
print (arr1[2])

# 원소가 boolean data type인 array 생성
arr10= np.array([True, True, False, False, False])
print (arr10.dtype)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int32
(6,)
1
3
bool


In [22]:
# arr1의 배열  크기를 2차원 배열인 (2,3) 으로 변경하기
arr2 = arr1.reshape(2,3)
print (arr2)
# array의 자료형을 확인할 수 있다.
print (arr2.dtype)
# array의 형태(크기)를 확인할 수 있다.
print (arr2.shape)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)


In [24]:
print(np.arange(15))
a = np.arange(15).reshape(3, 5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [25]:
a.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [26]:
np.transpose(a)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [27]:
np.swapaxes(a, 0, 1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [28]:
print (np.zeros(10))
print (np.zeros((3,5)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [29]:
print (np.ones(10))
print (np.ones((3,5)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
print (np.arange(10))
print (np.arange(3,10))
print (np.arange(3,10, 2))

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[3 5 7 9]


In [31]:
arr1 = np.array([[1,2,3],[4,5,6]])
print (arr1)
print (arr1.shape)
arr2 = np.array([[10,11,12],[13,14,15]])
print (arr2)
print (arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[10 11 12]
 [13 14 15]]
(2, 3)


In [25]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [26]:
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [27]:
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [28]:
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [30]:
arr3 = np.array([10,11,12])
print (arr3)
print (arr3.shape)

[10 11 12]
(3,)


In [33]:
arr1 * arr3

array([[10, 22, 36],
       [40, 55, 72]])

In [31]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [40]:
# broadcasting 예제
np.arange(3) + 5

array([5, 6, 7])

In [32]:
# arr1 = (2,3)
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [41]:
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [38]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [42]:
np.arange(3).reshape(3,1) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [45]:
a = np.array([1,2,3])
b = np.array([1,2])
a+b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [46]:
a1 = np.arange(10)
print(a1)
# 첫번째 element 출력
print(a1[0])
# 네번째 element 출력
print(a1[3])
# 네번째 ~ 9번째 element 출력
print(a1[3:9])
print(a1[:])
print(a1[::])

[0 1 2 3 4 5 6 7 8 9]
0
3
[3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [38]:
a2 = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
print(a2)
# 2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 합니다.
print(a2[0,0])
# 2행의 모든 element 출력
print(a2[2,:])
# 2행의 4번째 element 출력
print(a2[2,3])
# 모든 열의 4번째 element 출력
print(a2[:,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[ 9 10 11 12]
12
[ 4  8 12]


In [47]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
print(names)
print(names.shape)

['Beomwoo' 'Beomwoo' 'Kim' 'Joan' 'Lee' 'Beomwoo' 'Park' 'Beomwoo']
(8,)


In [50]:
# np.random.randn() 함수 : 기대값(평균값)이 0이고, 표준편차가 1인 가우시안 정규 분포를 따르는 난수를 발생시키는 함수이다.
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재한다.
data = np.random.randn(8,4)
print(data)
print(data.shape)

[[ 1.10624979 -1.30889768 -0.73395624  0.03050751]
 [-0.95151086 -0.64221062 -0.56619541  0.97785195]
 [-1.39531292 -0.2102204  -1.02207432 -0.36547921]
 [ 0.43826673 -1.11312098 -0.58650134  0.51299541]
 [-0.83645732  0.40208761  0.25064533  1.64160146]
 [ 0.70514988  1.87712526 -0.48825558 -1.18825168]
 [ 1.05546947  1.39208555 -0.175478   -0.07499263]
 [ 0.43583543  0.37458438  2.11781537 -1.11505998]]
(8, 4)


In [51]:
# 요소가 Beomwoo인 항목에 대한 mask 생성
names_Beomwoo_mask = (names == 'Beomwoo')
# names_Beomwoo_mask = (names == ['Beomwoo','Beomwoo','Beomwoo','Beomwoo','Beomwoo','Beomwoo','Beomwoo','Beomwoo'])
print(names_Beomwoo_mask)
# data에서 names_Beomwoo_mask가 True인 행들만 가져옴
print(data[names_Beomwoo_mask,:])
# print(data[[ True  True False False False  True False  True],:])
# 요소가 Kim인 행의 데이터만 꺼내기
print(data[names == 'Kim',:])
# 논리 연산을 응용하여, 요소가 Kim 또는 Park인 행의 데이터만 꺼내기
# | : or
print(data[(names == 'Kim') | (names == 'Park'),:])

[ True  True False False False  True False  True]
[[ 1.10624979 -1.30889768 -0.73395624  0.03050751]
 [-0.95151086 -0.64221062 -0.56619541  0.97785195]
 [ 0.70514988  1.87712526 -0.48825558 -1.18825168]
 [ 0.43583543  0.37458438  2.11781537 -1.11505998]]
[[-1.39531292 -0.2102204  -1.02207432 -0.36547921]]
[[-1.39531292 -0.2102204  -1.02207432 -0.36547921]
 [ 1.05546947  1.39208555 -0.175478   -0.07499263]]


In [52]:
# data array에서 0번째 열이 0보다 작은 element의 boolean 값
print(data[:,0] < 0)
# 첫번째 열의 값이 0보다 작은 행들을 출력
print(data[data[:,0]<0,:])
# print(data[[False  True  True False  True False False False],:])
# 첫번째 열의 값이 0보다 작은 행의 3,4번째 열 값
print(data[data[:,0]<0,2:4])
# 첫번째 열의 값이 0보다 작은 행의 3,4번째 열 값을 0으로 setting
data[data[:,0]<0,2:4] = 0
print(data)

[False  True  True False  True False False False]
[[-0.95151086 -0.64221062 -0.56619541  0.97785195]
 [-1.39531292 -0.2102204  -1.02207432 -0.36547921]
 [-0.83645732  0.40208761  0.25064533  1.64160146]]
[[-0.56619541  0.97785195]
 [-1.02207432 -0.36547921]
 [ 0.25064533  1.64160146]]
[[ 1.10624979 -1.30889768 -0.73395624  0.03050751]
 [-0.95151086 -0.64221062  0.          0.        ]
 [-1.39531292 -0.2102204   0.          0.        ]
 [ 0.43826673 -1.11312098 -0.58650134  0.51299541]
 [-0.83645732  0.40208761  0.          0.        ]
 [ 0.70514988  1.87712526 -0.48825558 -1.18825168]
 [ 1.05546947  1.39208555 -0.175478   -0.07499263]
 [ 0.43583543  0.37458438  2.11781537 -1.11505998]]


In [53]:
arr1 = np.random.randn(5,3)
print(arr1)

[[ 0.65478026  0.52162892 -0.25561032]
 [-0.83322712 -0.91260114  0.78950984]
 [-0.21911069 -0.50022931 -0.0177804 ]
 [-1.06925347  1.38096058  0.52497812]
 [-0.54982038  0.19921616  0.71562007]]


In [54]:
# 각 성분의 절대값 계산하기
np.abs(arr1)

array([[0.65478026, 0.52162892, 0.25561032],
       [0.83322712, 0.91260114, 0.78950984],
       [0.21911069, 0.50022931, 0.0177804 ],
       [1.06925347, 1.38096058, 0.52497812],
       [0.54982038, 0.19921616, 0.71562007]])

In [55]:
# 각 성분의 제곱근 계산하기 ( == array ** 0.5)
np.sqrt(arr1)
# nan : Not a Number

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([[0.80918493, 0.72223882,        nan],
       [       nan,        nan, 0.88854366],
       [       nan,        nan,        nan],
       [       nan, 1.17514279, 0.72455374],
       [       nan, 0.44633637, 0.8459433 ]])

In [46]:
# 각 성분의 제곱 계산하기
np.square(arr1)

array([[0.68394036, 0.71769496, 0.26850025],
       [2.0011427 , 0.15857713, 3.04565723],
       [0.7525532 , 0.67933202, 0.43222413],
       [0.68760879, 0.94006481, 1.20465704],
       [0.00327074, 0.09694809, 1.38442894]])

In [48]:
# 각 성분을 무리수 e의 지수로 삼은 값을 계산하기
np.exp(arr1)

array([[2.2864648 , 2.33303218, 1.67895251],
       [0.24301855, 0.671516  , 5.72693878],
       [2.38094684, 0.4385787 , 1.92984087],
       [0.43638875, 2.6368088 , 0.33368138],
       [1.05885734, 1.36528729, 0.30831984]])

In [49]:
# 각 성분을 자연로그, 상용로그, 밑이 2인 로그를 씌운 값을 계산하기
np.log(arr1)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


array([[-0.18994228, -0.16585533, -0.65745173],
       [        nan,         nan,  0.55685836],
       [-0.14214179,         nan, -0.4194055 ],
       [        nan, -0.03090323,         nan],
       [-2.86137013, -1.16678982,         nan]])

In [53]:
# 각 성분을 자연로그, 상용로그, 밑이 10인 로그를 씌운 값을 계산하기
np.log10(arr1)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log10
  


array([[-0.08249088, -0.07203005, -0.28552766],
       [        nan,         nan,  0.24184051],
       [-0.0617314 ,         nan, -0.1821455 ],
       [        nan, -0.0134211 ,         nan],
       [-1.24267726, -0.50673038,         nan]])

In [51]:
# 각 성분의 부호 계산하기(+인 경우 1, -인 경우 -1, 0인 경우 0)
np.sign(arr1)

array([[ 1.,  1.,  1.],
       [-1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1., -1.],
       [ 1.,  1., -1.]])

In [52]:
# 각 성분의 소수 첫 번째 자리에서 올림한 값을 계산하기
np.ceil(arr1)

array([[ 1.,  1.,  1.],
       [-1., -0.,  2.],
       [ 1., -0.,  1.],
       [-0.,  1., -1.],
       [ 1.,  1., -1.]])

In [54]:
# 각 성분의 소수 첫 번째 자리에서 내림한 값을 계산하기
np.floor(arr1)

array([[ 0.,  0.,  0.],
       [-2., -1.,  1.],
       [ 0., -1.,  0.],
       [-1.,  0., -2.],
       [ 0.,  0., -2.]])

In [55]:
# 각 성분이 NaN인 경우 True를, 아닌 경우 False를 반환하기
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [56]:
np.isnan(np.log(arr1))

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[False, False, False],
       [ True,  True, False],
       [False,  True, False],
       [ True, False,  True],
       [False, False,  True]])

In [57]:
# 각 성분이 무한대(infinity)인 경우 True를, 아닌 경우 False를 반환하기
np.isinf(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [58]:
# 각 성분에 대해 삼각함수 값을 계산하기(cos, cosh, sin, sinh, tan, tanh)
np.cos(arr1)

array([[ 0.67708146,  0.66210753,  0.86872697],
       [ 0.15554468,  0.92175369, -0.17350232],
       [ 0.64673669,  0.67913264,  0.79156072],
       [ 0.67544981,  0.56565468,  0.45576157],
       [ 0.99836508,  0.95191632,  0.38405004]])

In [56]:
np.tanh(arr1)

array([[ 0.57487921,  0.47895624, -0.25018516],
       [-0.68220501, -0.72237838,  0.65813127],
       [-0.21567028, -0.46229748, -0.01777853],
       [-0.7891798 ,  0.88116618,  0.48153299],
       [-0.50038558,  0.1966219 ,  0.61418894]])

In [57]:
print(arr1)
arr2 = np.random.randn(5,3)
print(arr2)

[[ 0.65478026  0.52162892 -0.25561032]
 [-0.83322712 -0.91260114  0.78950984]
 [-0.21911069 -0.50022931 -0.0177804 ]
 [-1.06925347  1.38096058  0.52497812]
 [-0.54982038  0.19921616  0.71562007]]
[[ 0.49197318  0.42189448  1.03470692]
 [-1.32878145  1.86110624 -0.158023  ]
 [-0.36527869  1.65507904 -1.01902061]
 [ 0.77307164 -0.21942812  0.09673373]
 [ 0.74097295  0.66874114 -0.46392974]]


In [58]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 연산 값을 계산하기
# (add, subtract, multiply, divide)
np.multiply(arr1,arr2)

array([[ 0.32213433,  0.22007236, -0.26448177],
       [ 1.10717675, -1.69844768, -0.12476072],
       [ 0.08003647, -0.82791904,  0.01811859],
       [-0.82660953, -0.30302159,  0.05078309],
       [-0.40740203,  0.13322404, -0.33199743]])

In [59]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 비교하여 
# 최대값 또는 최소값 계산하기(maximum, minimum)
np.maximum(arr1,arr2)

array([[ 0.65478026,  0.52162892,  1.03470692],
       [-0.83322712,  1.86110624,  0.78950984],
       [-0.21911069,  1.65507904, -0.0177804 ],
       [ 0.77307164,  1.38096058,  0.52497812],
       [ 0.74097295,  0.66874114,  0.71562007]])

In [60]:
print(arr1)

[[ 0.65478026  0.52162892 -0.25561032]
 [-0.83322712 -0.91260114  0.78950984]
 [-0.21911069 -0.50022931 -0.0177804 ]
 [-1.06925347  1.38096058  0.52497812]
 [-0.54982038  0.19921616  0.71562007]]


In [61]:
# 전체 성분의 합을 계산
np.sum(arr1)

0.42906111324453333

In [63]:
# 열 간의 합을 계산
np.sum(arr1, axis=0)

array([-2.01663141,  0.68897521,  1.75671731])

In [66]:
# 행 간의 합을 계산
np.sum(arr1, axis=0)

array([-0.49214385,  0.90566962,  0.64660251])

In [67]:
# 전체 성분의 평균을 계산
np.mean(arr1)

0.07067521821513824

In [68]:
# 행 간의 평균을 계산
np.mean(arr1, axis=0)

array([-0.09842877,  0.18113392,  0.1293205 ])

In [69]:
# 전체 성분의 표준편차, 분산, 최소값, 최대값 계산(std, var, min, max)
np.std(arr1)

0.9302929855458607

In [70]:
np.min(arr1, axis=1)

array([ 0.51817009, -1.41461751, -0.824216  , -1.0975687 , -1.17661758])

In [64]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스를 반환(argmin, argmax)
np.argmin(arr1)

9

In [65]:
np.argmax(arr1,axis=0)

array([0, 3, 1], dtype=int64)

In [66]:
# 맨 처음 성분부터 각 성분까지의 누적합 또는 누적곱을 계산(cumsum, cumprod)
# cumsum : cumulative summation(누적합)
np.cumsum(arr1)

array([ 0.65478026,  1.17640917,  0.92079885,  0.08757173, -0.82502941,
       -0.03551957, -0.25463026, -0.75485956, -0.77263996, -1.84189343,
       -0.46093285,  0.06404527, -0.48577511, -0.28655895,  0.42906111])

In [67]:
np.cumsum(arr1,axis=1)

array([[ 0.65478026,  1.17640917,  0.92079885],
       [-0.83322712, -1.74582826, -0.95631842],
       [-0.21911069, -0.71934   , -0.7371204 ],
       [-1.06925347,  0.31170712,  0.83668524],
       [-0.54982038, -0.35060423,  0.36501584]])

In [68]:
np.cumprod(arr1)

array([ 6.54780256e-01,  3.41552316e-01, -8.73042970e-02,  7.27443081e-02,
       -6.63865385e-02, -5.24128254e-02,  1.14842103e-02, -5.74473857e-03,
        1.02143749e-04, -1.09217557e-04, -1.50825142e-04, -7.91798995e-05,
        4.35347228e-05,  8.67282015e-06,  6.20644414e-06])

In [76]:
print(arr1)

[[ 0.82700687  0.84716879  0.51817009]
 [-1.41461751 -0.39821744  1.74518114]
 [ 0.86749824 -0.824216    0.65743755]
 [-0.8292218   0.9695694  -1.0975687 ]
 [ 0.05719035  0.31136488 -1.17661758]]


In [77]:
# 전체 성분에 대해서 오름차순으로 정렬
np.sort(arr1)

array([[ 0.51817009,  0.82700687,  0.84716879],
       [-1.41461751, -0.39821744,  1.74518114],
       [-0.824216  ,  0.65743755,  0.86749824],
       [-1.0975687 , -0.8292218 ,  0.9695694 ],
       [-1.17661758,  0.05719035,  0.31136488]])

In [78]:
# 전체 성분에 대해서 내림차순으로 정렬
np.sort(arr1)[::-1]

array([[-1.17661758,  0.05719035,  0.31136488],
       [-1.0975687 , -0.8292218 ,  0.9695694 ],
       [-0.824216  ,  0.65743755,  0.86749824],
       [-1.41461751, -0.39821744,  1.74518114],
       [ 0.51817009,  0.82700687,  0.84716879]])

In [79]:
# 행 방향으로 오름차순으로 정렬
np.sort(arr1,axis=0)

array([[-1.41461751, -0.824216  , -1.17661758],
       [-0.8292218 , -0.39821744, -1.0975687 ],
       [ 0.05719035,  0.31136488,  0.51817009],
       [ 0.82700687,  0.84716879,  0.65743755],
       [ 0.86749824,  0.9695694 ,  1.74518114]])